disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- identifier_name
- force_cast
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- SocialCAM/Vendors
- R.generated.swift
- R.shared.generated.swift
- R.mediaShared.generated.swift
- R.viralcam.generated.swift
- R.viralvids.generated.swift
- R.timespeed.generated.swift
- R.pic2art.generated.swift
- R.boomicam.generated.swift

line_length:
    warning: 150
    error: 1500
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

function_body_length:
    warning: 300
    error: 500

function_parameter_count:
    warning: 6
    error: 8

type_body_length:
    warning: 300
    error: 1000

file_length:
    warning: 1000
    error: 5500
    ignore_comment_only_lines: true

cyclomatic_complexity:
    warning: 115
    error: 125

reporter: "xcode"
