disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- identifier_name

- type_name
- empty_count

opt_in_rules:
- empty_count
- empty_string

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- SocialCAM/Vendors
- R.generated.swift

line_length:
    warning: 1150
    error: 1500
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

function_body_length:
    warning: 1300
    error: 1500

function_parameter_count:
    warning: 6
    error: 8

type_body_length:
    warning: 2300
    error: 2500

file_length:
    warning: 21000
    error: 29500
    ignore_comment_only_lines: true

cyclomatic_complexity:
    warning: 115
    error: 125

reporter: "xcode"
