# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StoriCam' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StoriCam
   pod 'R.swift', '5.0.3'
   pod 'ObjectMapper', '3.4.2'
   pod 'SDWebImage'
   pod 'AWSS3', '2.9.1'
   pod 'Moya-ObjectMapper/RxSwift', '2.8.0'
   pod 'Moya/RxSwift', '12.0.1'
   pod 'RxSwift', '4.4.1'
   pod 'Alamofire', '4.8.1'
   pod 'TGPControls', '5.1.0'
   pod 'Toast-Swift', '4.0.1'
   pod 'SCRecorder', :git => 'https://github.com/jasminpsimform/SCRecorder'
   pod 'Gemini', '1.3.1'
   pod 'OnlyPictures', :git => 'https://github.com/simformsolutions/OnlyPictures'
   pod 'FLAnimatedImage'
   pod 'RxAlamofire', '4.3.0'
   pod 'RxCocoa', '4.4.1'
   pod 'NSObject+Rx', '4.4.1'
   pod 'RxDataSources', '3.1.0'
   pod 'SVProgressHUD', '2.2.5'
   pod 'SwiftVideoGenerator', :git => 'https://github.com/jasminpsimform/swift-video-generator'
   pod 'URLEmbeddedView', '0.17.1'
end
